const REPORT = {
  title: "Model Benchmarking Q2 2026",
  subtitle: "Frontier intelligence, measured",
  edition: "Q2–Q3 2026 · Updated 3 September 2026",
  disclaimer:
    "Scores are compiled from vendor launch tables and independent boards (Artificial Analysis, vals.ai, DeepSWE, BenchLM). Harnesses, effort levels, and tool settings differ. Treat rankings as directional, not a single procurement score.",
};

const MODELS = [
  {
    id: "hy4",
    short: "Hy4",
    name: "Hy4 Preview",
    vendor: "Tencent Hunyuan",
    released: "28 Aug 2026",
    tag: "Open-weight flagship",
    color: "#ff7a1a",
    access: "Open weights + API",
    openness: "Open",
    license: "Apache 2.0",
    architecture: "MoE · Gated DeepSeek Sparse Attention",
    paramsTotal: "770B",
    paramsActive: "49B",
    layers: 78,
    experts: "256 routed + 1 shared · top-8",
    context: "1,048,576",
    contextK: 1048,
    maxOut: "64K",
    modalities: "Text",
    reasoning: "High (toggleable)",
    knowledge: "2026 (preview)",
    priceIn: 0.834,
    priceOut: 2.501,
    priceCache: 0.042,
    speedNote: "Native MTP speculative decoding (10B / 0.7B active)",
    apiId: "hy4-preview · tencent/hy4-preview",
    host: "Tencent Cloud TokenHub, OpenRouter, self-host (vLLM / SGLang, TP8)",
    hardware: "8-GPU cluster typical · FP8 ~780GB aggregate · not a workstation model",
    architectureNotes: [
      "78-layer MoE: dense FFN on layer 1, MoE on the remaining 77.",
      "Gated DSA with IndexCache; 4 residual streams (iHC).",
      "Native multi-token prediction layer for speculative decoding.",
    ],
    strengths: [
      "Apache 2.0 at 770B class — rare commercial freedom at this scale",
      "Strong agentic coding and tool-use for an open model",
      "Aggressive API pricing with 95% cache-hit discount",
    ],
    limits: [
      "Self-hosting needs a multi-GPU supernode, not a single card",
      "Preview release — Tencent still collecting production feedback",
      "Trails closed flagships on pure reasoning (CritPt, HLE)",
    ],
    bestFor: [
      "Self-hosted coding agents under Apache 2.0",
      "Office / productivity copilots (CodeBuddy, WorkBuddy)",
      "Cost-sensitive long-context RAG and tool calling",
    ],
    notFor: [
      "Consumer-GPU local inference",
      "Restricted cyber / life-science dual-use work",
    ],
    scores: {
      tb21: 85.4,
      swePro: 65.7,
      deepswe: 64.3,
      gpqa: 92.3,
      hle: 55.4,
      osworld: null,
      gdpval: null,
      aaIndex: null,
    },
    scoreNotes: {
      hle: "With tools, high effort (Tencent / DataLearner)",
      tb21: "Vendor-published, high effort",
    },
  },
  {
    id: "kimi",
    short: "Kimi K3",
    name: "Moonshot Kimi K3",
    vendor: "Moonshot AI",
    released: "16 Jul 2026",
    tag: "Largest open model",
    color: "#5b8cff",
    access: "Open weights + API",
    openness: "Open",
    license: "Kimi K3 License (custom)",
    architecture: "MoE · Kimi Delta Attention + AttnRes",
    paramsTotal: "2.8T",
    paramsActive: "104B",
    layers: 93,
    experts: "896 routed · 16 active + 2 shared",
    context: "1,048,576",
    contextK: 1048,
    maxOut: "—",
    modalities: "Text, image, video",
    reasoning: "Always on · low / high / max (default max)",
    knowledge: "2026",
    priceIn: 3.0,
    priceOut: 15.0,
    priceCache: 0.3,
    speedNote: "~33 tok/s (Artificial Analysis) · KDA up to 6.3× faster decode at 1M",
    apiId: "kimi-k3",
    host: "Kimi API, Kimi Work, Kimi Code · vLLM / SGLang / TokenSpeed",
    hardware: "1.56 TB MXFP4 shards · ≥64 accelerators recommended",
    architectureNotes: [
      "69 KDA layers + 24 Gated MLA; Attention Residuals across depth.",
      "Stable LatentMoE: 16 of 896 experts, ~2.5× scaling efficiency vs K2.",
      "MoonViT-V2 vision encoder (401M). QAT in MXFP4 / MXFP8.",
    ],
    strengths: [
      "World’s first open 3T-class model — downloadable frontier weights",
      "Top open-weight Artificial Analysis Intelligence Index (57)",
      "Leads several agent boards (BrowseComp, MCPMark, SWE-Marathon)",
    ],
    limits: [
      "Custom licence: MaaS revenue >$20M needs a separate agreement",
      "Slowest in the frontier group on output speed",
      "Self-host is lab / cluster only",
    ],
    bestFor: [
      "Auditable open-weight frontier research",
      "Million-token coding and knowledge-work agents",
      "Multimodal long-context (text + image + video)",
    ],
    notFor: [
      "Hyperscale resale without a Moonshot commercial deal",
      "Latency-critical chat",
    ],
    scores: {
      tb21: 88.3,
      swePro: 63.3,
      deepswe: 67.5,
      gpqa: 93.5,
      hle: 56.0,
      osworld: 58.3,
      gdpval: 1686,
      aaIndex: 57,
    },
    scoreNotes: {
      osworld: "OSWorld 2.0 (Moonshot table)",
      hle: "With tools",
    },
  },
  {
    id: "fable",
    short: "Fable 5.1",
    name: "Claude Fable 5.1",
    vendor: "Anthropic",
    released: "1 Sep 2026",
    tag: "Coding & knowledge work",
    color: "#d4a574",
    access: "Generally available",
    openness: "Closed",
    license: "Proprietary API",
    architecture: "Closed transformer · adaptive thinking always on",
    paramsTotal: "Undisclosed",
    paramsActive: "Undisclosed",
    layers: "—",
    experts: "—",
    context: "1,000,000",
    contextK: 1000,
    maxOut: "128K",
    modalities: "Text, image, documents",
    reasoning: "Adaptive · effort low–max (default high in Claude Code)",
    knowledge: "June 2026",
    priceIn: 10.0,
    priceOut: 50.0,
    priceCache: 0.25,
    speedNote: "Slower class · 5m cache write $12.50 · 1h cache write $20",
    apiId: "claude-fable-5-1",
    host: "Claude API, Bedrock, Google Cloud, Microsoft Foundry",
    hardware: "Hosted only",
    architectureNotes: [
      "Same underlying weights as Mythos 5.1; production safeguards on.",
      "1M context at standard token prices across the full window.",
      "Cache reads cut 75% vs Fable 5 ($1.00 → $0.25 / MTok).",
    ],
    strengths: [
      "Best generally-available model for long-horizon coding and research",
      "52.6% Terminal-Bench-Science — roughly 2× Fable 5",
      "Cheaper persistent agents via $0.25 cache reads (~25–45% lower TCO)",
    ],
    limits: [
      "Highest list price in this set ($10 / $50)",
      "Safeguards zero some cyber / bio tasks ( Mythos is the unrestricted twin)",
      "Breaking API changes vs Fable 5 (forced tools, thinking-block binding)",
    ],
    bestFor: [
      "Multi-day agentic coding and repo work",
      "Scientific research agents and document / spreadsheet / slide work",
      "Enterprises that need generally-available frontier quality",
    ],
    notFor: [
      "Authorized exploit-class cyber research (use Mythos or GPT-5.6 Cyber)",
      "Budget high-volume inference",
    ],
    scores: {
      tb21: null,
      tb40: 55.8,
      tbScience: 52.6,
      swePro: 81.2,
      deepswe: null,
      gpqa: null,
      hle: 60.9,
      hleTools: 65.0,
      osworld: 77.9,
      osworldStrict: 41.7,
      gdpval: 1853,
      cursorBench: 73.4,
      automation: 31.4,
      aaIndex: null,
    },
    scoreNotes: {
      swePro: "BenchLM, Sep 2026",
      osworld: "OSWorld 2.0 partial, Aug 2026 task release",
      hle: "No tools",
      tb40: "Terminal-Bench 4.0 (not 2.1)",
    },
  },
  {
    id: "mythos",
    short: "Mythos 5.1",
    name: "Claude Mythos 5.1",
    vendor: "Anthropic",
    released: "1 Sep 2026",
    tag: "Trusted-access twin",
    color: "#9b7ed9",
    access: "Project Glasswing only",
    openness: "Closed · restricted",
    license: "Proprietary · vetted access",
    architecture: "Identical weights to Fable 5.1 · permissive safeguards",
    paramsTotal: "Undisclosed",
    paramsActive: "Undisclosed",
    layers: "—",
    experts: "—",
    context: "1,000,000",
    contextK: 1000,
    maxOut: "128K",
    modalities: "Text, image, documents",
    reasoning: "Adaptive · effort low–max",
    knowledge: "June 2026",
    priceIn: 10.0,
    priceOut: 50.0,
    priceCache: 0.25,
    speedNote: "Same serving profile as Fable 5.1",
    apiId: "claude-mythos-5-1",
    host: "Project Glasswing · Anthropic / AWS / GCP account teams",
    hardware: "Hosted only · US orgs first, expanding",
    architectureNotes: [
      "Same model as Fable 5.1; safeguards relaxed for cyberdefense and life sciences.",
      "Does not enforce Fable’s prefix-binding check on edited thinking blocks.",
      "Biology capabilities gated by a US-government-partnered access program.",
    ],
    strengths: [
      "Highest Terminal-Bench 4.0 in this set (60.9%)",
      "Lab-validated protein binder design (~50% hit rate across 12 targets)",
      "Strongest Anthropic cyber capabilities with production-grade research access",
    ],
    limits: [
      "Not generally available — identity, legal, and program checks",
      "Still below Anthropic’s next RSP risk tier; biology remains gated",
      "Same $10 / $50 list price as Fable",
    ],
    bestFor: [
      "Vetted cyberdefense (vulnerability discovery, not public exploit kits)",
      "Computational biology, protein design, GPU-kernel scientific work",
      "Orgs blocked by Fable’s production safeguards on dual-use tasks",
    ],
    notFor: [
      "General product teams without Glasswing approval",
      "Public SaaS default model",
    ],
    scores: {
      tb21: null,
      tb40: 60.9,
      tbScience: 52.6,
      swePro: 80.3,
      deepswe: null,
      gpqa: null,
      hle: 60.9,
      hleTools: 65.0,
      osworld: 77.9,
      gdpval: 1853,
      aaIndex: null,
    },
    scoreNotes: {
      tb40: "Mythos 5.1 published separately from Fable 5.1 (55.8%)",
      swePro: "BenchLM row for Mythos 5 (80.3%); 5.1 shares Fable quality",
    },
  },
  {
    id: "glm",
    short: "GLM Flash",
    name: "GLM-5.3 Flash",
    vendor: "Z.ai (Zhipu)",
    released: "26 Aug 2026",
    tag: "Frontier at flash cost",
    color: "#3ddc97",
    access: "Open weights + API",
    openness: "Open",
    license: "MIT",
    architecture: "MoE · hybrid linear + sparse attention · mHC",
    paramsTotal: "320B",
    paramsActive: "18B",
    layers: 45,
    experts: "288 routed + 1 shared · 8 active",
    context: "1,048,576",
    contextK: 1048,
    maxOut: "128K (API) / 163K card",
    modalities: "Text, image, video, file",
    reasoning: "low / high / max (default max)",
    knowledge: "2026",
    priceIn: 0.15,
    priceOut: 0.5,
    priceCache: null,
    speedNote: "3.01× less attention compute and 4.44× smaller KV vs GLM-5.3",
    apiId: "glm-5.3-flash",
    host: "Z.ai API · Hugging Face MIT weights · llama.cpp / SGLang / vLLM",
    hardware: "Local: 100GB+ even quantized · 128–256GB RAM class",
    architectureNotes: [
      "First GLM-5 natively multimodal model; 30T-token multimodal pretrain.",
      "34 linear-attention + 11 sparse-attention layers.",
      "Manifold-Constrained Hyper-Connections (mHC) for scaling efficiency.",
    ],
    strengths: [
      "Cheapest frontier-adjacent API in this set ($0.15 / $0.50)",
      "MIT licence — unrestricted commercial use, fine-tune, redistribute",
      "AA Intelligence Index 57, tied with Kimi K3 among open models",
    ],
    limits: [
      "Still a workstation/cluster local deploy, not a 24GB card",
      "HLE without tools (39.9) trails closed flagships",
      "Not the SWE-Pro leader",
    ],
    bestFor: [
      "High-volume production agents where unit cost dominates",
      "Commercial products that need a truly permissive licence",
      "Multimodal long-context at Flash economics",
    ],
    notFor: [
      "Maximum SWE-Pro / science-agent quality (use Fable)",
      "Laptop-only inference",
    ],
    scores: {
      tb21: 84.3,
      swePro: null,
      deepswe: 63.4,
      gpqa: 91.2,
      hle: 39.9,
      hleTools: 55.3,
      osworld: null,
      gdpval: 1773,
      aaIndex: 57,
    },
    scoreNotes: {
      hle: "AA, no tools",
      tb21: "AA independently matched Z.ai’s 84.3",
      gdpval: "Elo",
    },
  },
  {
    id: "gemini",
    short: "Gemini 3.8",
    name: "Gemini 3.8 Flash",
    vendor: "Google DeepMind",
    released: "2 Sep 2026",
    tag: "Fast workhorse",
    color: "#4b8bf5",
    access: "Generally available",
    openness: "Closed",
    license: "Proprietary API",
    architecture: "Gemini 3.7 Flash lineage · configurable thinking",
    paramsTotal: "Undisclosed",
    paramsActive: "Undisclosed",
    layers: "—",
    experts: "—",
    context: "1,048,576",
    contextK: 1048,
    maxOut: "65,536",
    modalities: "Text, image, audio, video, PDF → text",
    reasoning: "thinking_level LOW / MEDIUM / HIGH",
    knowledge: "March 2026 (some domains Jan 2025)",
    priceIn: 0.75,
    priceOut: 3.75,
    priceCache: null,
    speedNote: "~305 tok/s at high reasoning (Artificial Analysis)",
    apiId: "gemini-3.8-flash",
    host: "Gemini API, AI Studio, Vertex, Antigravity, Gemini app (Pro/Ultra)",
    hardware: "Hosted only",
    architectureNotes: [
      "Built on Gemini 3.7 Flash; third Flash drop in six weeks.",
      "Thinking levels replace temperature / top-p for quality–cost control.",
      "Intro price through 31 Dec 2026; doubles on 1 Jan 2027 ($1.50 / $7.50).",
    ],
    strengths: [
      "DeepSWE 74% — tied for the board’s top spot with Opus 5",
      "Fastest generally-available model here (~305 tok/s)",
      "Leads specialist agent benches (Vals Finance 61.4, Harvey Legal 10.0)",
    ],
    limits: [
      "Weak on Terminal-Bench 4.0 (19.1%) vs Claude’s 50%+ class",
      "Intro pricing expires end of 2026",
      "Computer-use still Preview; no image/audio generation",
    ],
    bestFor: [
      "High-throughput coding agents and production APIs",
      "Multimodal ingestion (audio / video / PDF) at Flash cost",
      "Finance, legal, and Search-grounded enterprise agents",
    ],
    notFor: [
      "Hardest terminal / OS-world agent evals (Claude still leads)",
      "Teams that need price locked past Dec 2026 without a budget reset",
    ],
    scores: {
      tb21: 87.6,
      swePro: null,
      sweVerified: 80.0,
      deepswe: 74.0,
      gpqa: 94.4,
      hle: 47.8,
      hleVerified: 54.9,
      osworld: 59.0,
      gdpval: 1545,
      aaIndex: 59,
      livecode: 89.5,
    },
    scoreNotes: {
      tb21: "Artificial Analysis 87.6; Google quotes 89.4",
      deepswe: "High effort, DeepSWE board — tied with Opus 5",
      hle: "AA, no tools",
      osworld: "OSWorld 2.0 vs Fable 5.1’s 77.9 partial",
    },
  },
  {
    id: "gptcyber",
    short: "GPT-5.6 Cyber",
    name: "GPT-5.6 Cyber",
    vendor: "OpenAI",
    released: "10 Aug 2026",
    tag: "Daybreak Red",
    color: "#10a37f",
    access: "Daybreak Red only",
    openness: "Closed · restricted",
    license: "Proprietary · authorized defenders",
    architecture: "Purpose-trained on GPT-5.6 Sol",
    paramsTotal: "Undisclosed",
    paramsActive: "Undisclosed",
    layers: "—",
    experts: "—",
    context: "400,000",
    contextK: 400,
    maxOut: "128,000",
    modalities: "Text + image → text",
    reasoning: "Reasoning tokens supported",
    knowledge: "16 Feb 2026",
    priceIn: 12.5,
    priceOut: 75.0,
    priceCache: 1.25,
    speedNote: ">272K input billed 2× input / 1.5× output for the full request",
    apiId: "gpt-5.6-cyber · alias daybreak-red-latest",
    host: "OpenAI Responses API (Chat Completions not supported)",
    hardware: "Hosted · FIDO hardware keys required for individuals from 1 Sep 2026",
    architectureNotes: [
      "Specialized Sol checkpoint for authorized vulnerability research.",
      "Preparedness cyber rating: High (below Critical), OpenAI self-report.",
      "Daybreak Blue (Sol) is the recommended start for most defenders.",
    ],
    strengths: [
      "95% completion on OpenAI’s Advanced Cybersecurity Completion Rate vs ~1.5–2% for Sol",
      "Beats Sol on ExploitGym and internal zero-day work",
      "Built for approved patch validation, vuln research, and security testing",
    ],
    limits: [
      "No public GA — identity, monitoring, legal attestations",
      "Lags Sol on vuln-report writing and ExploitBench 300-turn efficiency",
      "Most expensive list price here; smaller context than 1M-class models",
    ],
    bestFor: [
      "Approved red-team / vuln-research programs (Daybreak Red)",
      "Exploit-chain validation in controlled lab environments",
      "Defenders who hit refusal walls on Sol / Fable",
    ],
    notFor: [
      "General coding, chat, or unvetted production apps",
      "Anyone outside Daybreak",
    ],
    scores: {
      tb21: null,
      swePro: null,
      deepswe: null,
      gpqa: null,
      hle: null,
      osworld: null,
      gdpval: null,
      cyberComplete: 95.0,
      aaIndex: null,
    },
    scoreNotes: {
      cyberComplete: "OpenAI Advanced Cybersecurity Completion Rate (self-reported)",
    },
  },
  {
    id: "muse",
    short: "Glimmer",
    name: "Muse Glimmer 30B",
    vendor: "Meta Superintelligence Labs",
    released: "10 Aug 2026",
    tag: "Local agent",
    color: "#66d4ff",
    access: "Open weights (consumer GPU)",
    openness: "Open",
    license: "Apache 2.0 + Meta Usage Policy",
    architecture: "Dense causal transformer + ViT-G/14 encoder",
    paramsTotal: "29.6B",
    paramsActive: "29.6B dense",
    layers: 52,
    experts: "Dense · GQA 32Q / 2KV",
    context: "131,072",
    contextK: 131,
    maxOut: "Shared 131K window",
    modalities: "Text + image → text (video as sampled frames)",
    reasoning: "low / medium / high / xhigh",
    knowledge: "4 Jan 2026",
    priceIn: 0,
    priceOut: 0,
    priceCache: 0,
    speedNote: "DFlash speculative drafter · K-Quant-17GB targets 24GB GPUs",
    apiId: "meta-models/Muse-Glimmer-30B",
    host: "llama.cpp, Ollama, LM Studio, vLLM, Together / Fireworks / OpenRouter (launch partners)",
    hardware: "24GB (K-Quant-17GB) · 32GB dynamic · ~60GB BF16",
    architectureNotes: [
      "Distilled from Muse Spark. 1.8B ViT-G/14 perception encoder.",
      "Repeating local/local/local/global attention; sliding window 2048.",
      "Official GGUFs + DFlash drafter; 100+ training languages.",
    ],
    strengths: [
      "Only model in this set that realistically runs on one 24GB GPU",
      "Leads several small-model agent benches (MCP Atlas 75.5, GAIA2 43.3)",
      "Apache 2.0 weights — private, air-gapped agents",
    ],
    limits: [
      "Not frontier on SWE-Pro (51.2) or HLE (22.0)",
      "131K context, not 1M; Qwen 27B class still wins some agent rows",
      "Open-weight ≠ fully open-source (no full training data)",
    ],
    bestFor: [
      "Always-on local coding and tool-using agents",
      "Privacy-sensitive laptop / workstation deployments",
      "LLM-as-judge and multimodal screenshot workflows on-device",
    ],
    notFor: [
      "Replacing Fable / K3 on million-token or SWE-Pro work",
      "Audio-native or image-generation pipelines",
    ],
    scores: {
      tb21: 51.7,
      swePro: 51.2,
      sweVerified: 76.0,
      deepswe: null,
      gpqa: 83.5,
      hle: 22.0,
      osworld: 65.9,
      gdpval: 953,
      mcpAtlas: 75.5,
      aime: 94.7,
      aaIndex: null,
    },
    scoreNotes: {
      osworld: "OSWorld-Verified (Meta table)",
      tb21: "Artificial Analysis",
    },
  },
  {
    id: "qwen",
    short: "Qwen 3.8",
    name: "Qwen3.8-Max",
    vendor: "Alibaba Qwen",
    released: "3 Aug 2026",
    tag: "Long-horizon cowork",
    color: "#c084fc",
    access: "API + open weights",
    openness: "Open",
    license: "Custom qwen3.8-max (not Apache)",
    architecture: "MoE · Gated DeltaNet + Gated Attention",
    paramsTotal: "2.4T",
    paramsActive: "95B",
    layers: "—",
    experts: "Sparse MoE · 95B active",
    context: "1,000,000",
    contextK: 1000,
    maxOut: "131K",
    modalities: "Text, image, video (API) · open ckpt text-first",
    reasoning: "xhigh (default) / medium / low",
    knowledge: "2026",
    priceIn: 2.0,
    priceOut: 6.0,
    priceCache: 0.25,
    speedNote: "Managed max input 991K · open checkpoint native 262K, extensible ~1.01M",
    apiId: "qwen3.8-max · Qwen3.8-2.4T-A95B",
    host: "QwenCloud, Alibaba Cloud Model Studio, Hugging Face / ModelScope",
    hardware: "Cluster-scale for 2.4T · API is the practical path for most teams",
    architectureNotes: [
      "First Max-class Qwen with published weights.",
      "Vision as a closed feedback loop: plan → act → inspect → correct.",
      "Custom licence: extra terms if MaaS revenue exceeds $50M.",
    ],
    strengths: [
      "PaperBench 93.0 and OSWorld-Verified 86.1 — top published rows",
      "Documented 10+ day autonomous coding runs",
      "Strong instruction following (IFBench 82.8) and multimodal math (95.2)",
    ],
    limits: [
      "HLE 43.6 — last among the 2T-class flagships",
      "SWE-Pro 67.7 trails Fable 5.1’s 81.2",
      "Licence is not Apache; revenue gates on large MaaS",
    ],
    bestFor: [
      "Computer-use / hybrid GUI+code agents",
      "Multi-day autonomous coding and professional cowork",
      "Research-paper reproduction and long video / document agents",
    ],
    notFor: [
      "HLE-style multidisciplinary exams vs Claude",
      "Shops that require OSI-approved Apache/MIT only",
    ],
    scores: {
      tb21: 86.6,
      swePro: 67.7,
      deepswe: null,
      gpqa: 92.6,
      hle: 43.6,
      osworld: 86.1,
      gdpval: null,
      paperbench: 93.0,
      ifbench: 82.8,
      mathvision: 95.2,
      aaIndex: null,
    },
    scoreNotes: {
      osworld: "OSWorld-Verified",
      hle: "Text, vendor table vs Fable 5",
    },
  },
  {
    id: "gpt6astra",
    short: "GPT 6 Astra",
    name: "GPT 6 Astra",
    vendor: "OpenAI",
    released: "Unannounced",
    tag: "Awaiting verification",
    color: "#10a37f",
    access: "No verified public access",
    openness: "Closed",
    license: "Not published",
    architecture: "Not published",
    paramsTotal: "Undisclosed",
    paramsActive: "Undisclosed",
    layers: "—",
    experts: "—",
    context: "Unpublished",
    contextK: null,
    maxOut: "Unpublished",
    modalities: "Unpublished",
    reasoning: "Unpublished",
    knowledge: "Unpublished",
    priceIn: null,
    priceOut: null,
    priceCache: null,
    speedNote: "No verified serving or latency information",
    apiId: "Not published",
    host: "No verified public endpoint",
    hardware: "Hosted status not announced",
    architectureNotes: [
      "GPT 6 Astra is included as an unverified placeholder requested for this report.",
      "Specifications will remain unpublished until a primary OpenAI source is available.",
    ],
    strengths: [
      "No verified capability claims are available yet",
    ],
    limits: [
      "No primary launch source, public benchmark results, or pricing",
      "Not suitable for procurement comparisons in its current placeholder state",
    ],
    bestFor: [
      "Tracking a future announcement once primary evidence is available",
    ],
    notFor: [
      "Production selection or benchmark ranking",
      "Cost, architecture, or capability comparisons",
    ],
    scores: {
      tb21: null,
      swePro: null,
      deepswe: null,
      gpqa: null,
      hle: null,
      osworld: null,
      gdpval: null,
      aaIndex: null,
    },
    scoreNotes: {},
  },
];

const BENCHMARKS = [
  {
    key: "tb21",
    label: "Terminal-Bench 2.1",
    unit: "%",
    higher: true,
    group: "coding",
    measures: "Command-line software agents",
    description:
      "The model is dropped into a real terminal and must install packages, inspect files, run tests, and finish a coding or ops task without a human in the loop. It is the workhorse eval for “can this model be a CLI coding agent?”",
    interpret:
      "High 80s is frontier. A 3–4 point gap is often noise (error bars on TB 2.1 are large). Harness choice (Claude Code vs Terminus) can move scores more than the model itself.",
    caveat: "Fable 5.1 / Mythos 5.1 published Terminal-Bench 4.0 instead of 2.1 — do not mix the two generations.",
    leader: "Kimi K3 88.3 (vendor) · Gemini 3.8 Flash 87.6 (Artificial Analysis)",
  },
  {
    key: "tb40",
    label: "Terminal-Bench 4.0",
    unit: "%",
    higher: true,
    group: "coding",
    measures: "Harder, longer-horizon terminal work",
    description:
      "The 2026 successor suite. Tasks run longer, leak less, and punish shortcut patches. Anthropic uses it as the headline agentic-coding number for Fable / Mythos 5.1.",
    interpret:
      "Mid-50s is excellent on this harder split. Mythos 5.1 at 60.9 vs Fable 5.1 at 55.8 is mostly safeguard policy (same weights), not a bigger brain.",
    caveat: "Not comparable to Terminal-Bench 2.1. Gemini 3.8 Flash is weak here (19.1) despite a strong TB 2.1 / DeepSWE showing.",
    leader: "Claude Mythos 5.1 60.9 · Fable 5.1 55.8",
  },
  {
    key: "tbScience",
    label: "Terminal-Bench-Science 0.1",
    unit: "%",
    higher: true,
    group: "science",
    measures: "End-to-end scientific investigation in a shell",
    description:
      "Plan an experiment, write and run analysis code, check results, and iterate. This is closer to a research assistant than to LeetCode. Anthropic quotes ±3.5–4.5 points of standard error.",
    interpret:
      "Fable 5.1 at 52.6 roughly doubles Fable 5 (24.7) and leads GPT-5.6 Sol (22.4) and Opus 5 (29.0) on Anthropic’s setup. Treat as a scientific-agent signal, not a coding-only signal.",
    caveat: "Public leaderboard harness and Anthropic’s internal reproduction differ by a few points; both are within noise.",
    leader: "Claude Fable 5.1 52.6",
  },
  {
    key: "swePro",
    label: "SWE-bench Pro",
    unit: "%",
    higher: true,
    group: "coding",
    measures: "Real GitHub / professional repo bug-fixing",
    description:
      "The model must localize a bug in a multi-file professional repository, write a patch, and pass hidden tests. Harder and less saturated than SWE-bench Verified.",
    interpret:
      "80+ is the closed-frontier cluster (Fable 5.1 81.2). Open models in this set sit in the mid-60s. A jump from 65 to 81 is a product-class difference for repo agents.",
    caveat: "OpenAI has flagged a share of public SWE-Pro tasks as broken. Use alongside DeepSWE and your own repos.",
    leader: "Claude Fable 5.1 81.2 (BenchLM, Sep 2026)",
  },
  {
    key: "sweVerified",
    label: "SWE-bench Verified",
    unit: "%",
    higher: true,
    group: "coding",
    measures: "Human-validated issue resolution",
    description:
      "A cleaner, smaller SWE-bench split where tasks were checked by engineers. Easier than Pro and closer to saturation at the frontier.",
    interpret:
      "High 70s–80 is expected for flagships. Useful as a sanity check, weak as a differentiator among 2026 frontier models.",
    caveat: "Do not treat Verified and Pro as the same benchmark.",
    leader: "Gemini 3.8 Flash 80.0 (vals.ai) · Muse Glimmer 76.0 (small-model class)",
  },
  {
    key: "deepswe",
    label: "DeepSWE v1.1",
    unit: "%",
    higher: true,
    group: "coding",
    measures: "Long-horizon, end-to-end software engineering",
    description:
      "Hours-long agent runs that must design, implement, test, and recover from failures. This is the eval that most closely tracks “leave it overnight on a hard engineering ticket.”",
    interpret:
      "70+ is rare. Gemini 3.8 Flash at 74 ties the published top of the board with Claude Opus 5. Kimi K3 (67.5) and Hy4 (64.3) are the open-weight pack.",
    caveat: "Timeout, context cap, and mini-swe-agent vs other scaffolds change Pass@1 by several points.",
    leader: "Gemini 3.8 Flash 74.0 (high effort, official board)",
  },
  {
    key: "gpqa",
    label: "GPQA Diamond",
    unit: "%",
    higher: true,
    group: "reasoning",
    measures: "Graduate-level science questions (PhD-hard)",
    description:
      "Google-proof Q&A written so that domain experts score well and skilled non-experts with search do not. A compact test of raw scientific reasoning without tools.",
    interpret:
      "The 2026 field is tightly clustered in the low-to-mid 90s. A 1-point gap is not a buying criterion. Muse Glimmer at 83.5 is the expected drop for a 30B local model.",
    caveat: "Saturated at the frontier — do not rank 2T-class models by GPQA alone.",
    leader: "Gemini 3.8 Flash 94.4 · Kimi K3 93.5",
  },
  {
    key: "hle",
    label: "Humanity’s Last Exam",
    unit: "%",
    higher: true,
    group: "reasoning",
    measures: "Broad, expert, anti-memorization knowledge",
    description:
      "A frontier exam spanning STEM, humanities, and professional domains, designed to resist benchmark gaming. Published both with and without tools; those two numbers are not interchangeable.",
    interpret:
      "Fable 5.1 leads this set at 60.9 (no tools) / 65.0 (with tools). Qwen3.8-Max’s 43.6 is the main warning label on an otherwise strong coding/agent model: it is not the general-knowledge king.",
    caveat: "Vendor “HLE with tools” (Hy4 55.4, GLM 55.3) is a different protocol from AA’s no-tools 39.9 for GLM.",
    leader: "Claude Fable 5.1 60.9 no-tools / 65.0 with tools",
  },
  {
    key: "osworld",
    label: "OSWorld / computer use",
    unit: "%",
    higher: true,
    group: "agents",
    measures: "Driving a real desktop like a human",
    description:
      "The agent sees screenshots, clicks, types, and completes office / OS tasks. OSWorld-Verified and OSWorld 2.0 (Aug 2026 task files) are different releases — we label the split in the score notes.",
    interpret:
      "Qwen3.8-Max 86.1 (Verified) is the published computer-use leader. Fable 5.1 leads the newer 2.0 partial split at 77.9 (41.7 strict). Muse Glimmer 65.9 is strong for 30B.",
    caveat: "Partial vs strict scoring, and old vs Aug-2026 task files, cannot be ranked in one column without the footnote.",
    leader: "Qwen3.8-Max 86.1 Verified · Fable 5.1 77.9 OSWorld 2.0 partial",
  },
  {
    key: "gdpval",
    label: "GDPval-AA v2",
    unit: "Elo",
    higher: true,
    group: "work",
    measures: "Professionally valuable knowledge work",
    description:
      "Artificial Analysis pairwise Elo over economically useful deliverables (briefings, analysis, office artifacts), not puzzles. Higher Elo = preferred more often by the judge panel.",
    interpret:
      "Fable 5.1 at 1853 is the work-product leader in this set. GLM-5.3 Flash at 1773 is remarkable for its price. Gemini 3.8 Flash (1545) and Muse (953) trail on this axis.",
    caveat: "Elo, not a percent. Never plot on the same axis as TB/SWE without rescaling.",
    leader: "Claude Fable 5.1 1853",
  },
];

const METHOD_STEPS = [
  {
    title: "1. Choose the job, then the bench",
    body: "A coding agent, a computer-use agent, a science assistant, and a local laptop model are different products. We map each public eval to a job: Terminal-Bench and DeepSWE for CLI agents, SWE-Pro for repo repair, OSWorld for GUI, HLE/GPQA for knowledge, GDPval for office deliverables.",
  },
  {
    title: "2. Separate vendor tables from independent boards",
    body: "Launch blogs run their own harness, effort, and sometimes their own scaffold. Where Artificial Analysis, vals.ai, DeepSWE’s board, or BenchLM published a number, we prefer it and footnote the vendor figure. Gold cells are the best published number inside this ten-model set — not a claim of a global SOTA.",
  },
  {
    title: "3. Hold effort and tools constant — or label when you cannot",
    body: "Max / xhigh / high / adaptive thinking are not the same knob. “HLE with tools” is a different test from “HLE no tools.” We never average them. Missing scores are shown as em-dashes, never as zero, so a specialist like GPT-5.6 Cyber is not punished for skipping SWE-Pro.",
  },
  {
    title: "4. Read error bars and harnesses before gaps",
    body: "Terminal-Bench 2.1 noise is often ±10 points. Terminal-Bench-Science quotes ±3.5–4.5. A one-point GPQA gap is saturated noise. Scaffold (Claude Code, mini-swe-agent, Terminus, OpenClaw) routinely outweighs the model delta. If two labs disagree, we show both and say so.",
  },
  {
    title: "5. Price the whole trajectory, not the sticker",
    body: "Agent runs reread huge prompts. Cache hits (Fable $0.25, Hy4 $0.042, Kimi $0.30) dominate TCO. Gemini’s intro rate doubles on 1 Jan 2027. Local models “cost” VRAM and watts. Restricted models cost access time, not just tokens.",
  },
];

const FINDINGS = [
  {
    title: "There is no single #1",
    body: "Fable 5.1 is the generally-available quality ceiling for long-horizon coding, science agents, and knowledge work. Gemini 3.8 Flash is the speed/cost coding workhorse (DeepSWE 74, ~305 tok/s). Qwen3.8-Max wins computer-use. Kimi K3 wins open-weight scale. GLM-5.3 Flash wins unit economics. Muse Glimmer wins “runs on one GPU.” Pick the axis you actually pay for.",
  },
  {
    title: "Open weights closed most of the coding gap — not HLE",
    body: "Kimi K3 (88.3 TB 2.1), Hy4 (85.4), GLM Flash (84.3) and Qwen (86.6) sit in the same Terminal-Bench band as closed Flash/Sol-class models. The remaining closed-model moat is SWE-Pro (Fable 81 vs open mid-60s), Terminal-Bench-Science, and HLE (Fable 60.9 vs Qwen 43.6).",
  },
  {
    title: "Specialist twins are policy, not extra parameters",
    body: "Fable 5.1 and Mythos 5.1 share weights; Mythos’s 60.9 vs 55.8 on TB 4.0 is safeguard permissiveness for vetted cyber and life-science orgs. GPT-5.6 Cyber is a Sol specialization: 95% completion on dual-use cyber prompts versus ~2% on Sol, at 2.5× Sol’s list price and a 400K — not 1M — window.",
  },
  {
    title: "Long context is now table stakes; serving it is not",
    body: "Seven of ten models advertise a ~1M token window. That does not mean they recall a million tokens equally, or that you can host them. Kimi K3 is 1.56 TB of MXFP4. Hy4 wants an 8-GPU node. GLM Flash is the first multimodal 1M model you might actually serve. Muse is 131K on purpose so a 24GB card can hold the KV cache. GPT 6 Astra remains unpublished and is excluded from this context comparison.",
  },
];

const USE_CASES = [
  {
    id: "coding",
    title: "Long-horizon agentic coding",
    pick: "fable",
    alt: "gemini",
    why: "Fable 5.1 leads SWE-bench Pro (81.2) and CursorBench 3.2 (73.4), and more than doubled Fable 5 on Terminal-Bench-Science. Gemini 3.8 Flash is the cheaper, faster runner-up on DeepSWE (74, tied for first).",
  },
  {
    id: "open",
    title: "Open-weight frontier",
    pick: "kimi",
    alt: "hy4",
    why: "Kimi K3 is the largest open model (2.8T / 104B active) and the top open AA Intelligence Index (57). Hy4 Preview is the Apache 2.0 alternative at far lower API cost.",
  },
  {
    id: "cost",
    title: "Cost-efficient production",
    pick: "glm",
    alt: "gemini",
    why: "GLM-5.3 Flash is $0.15 / $0.50 with MIT weights and a 1M window. Gemini 3.8 Flash is the hosted speed play at $0.75 / $3.75 (intro) and ~305 tok/s.",
  },
  {
    id: "local",
    title: "Local / private agents",
    pick: "muse",
    alt: "glm",
    why: "Muse Glimmer is the only model here that targets a single 24GB GPU. GLM-5.3 Flash is the next step up if you have 128GB+ memory and want MIT + 1M context.",
  },
  {
    id: "science",
    title: "Scientific research",
    pick: "fable",
    alt: "mythos",
    why: "Fable 5.1 posts 52.6% on Terminal-Bench-Science and 60.9% HLE without tools. Mythos 5.1 is the same intelligence with life-science safeguards relaxed for vetted labs.",
  },
  {
    id: "cyber",
    title: "Authorized cybersecurity",
    pick: "gptcyber",
    alt: "mythos",
    why: "GPT-5.6 Cyber is purpose-trained for Daybreak Red defenders (95% completion vs ~2% on Sol). Mythos 5.1 is Anthropic’s vetted twin when you already live in the Claude stack.",
  },
  {
    id: "computer",
    title: "Computer-use & multimodal agents",
    pick: "qwen",
    alt: "fable",
    why: "Qwen3.8-Max leads OSWorld-Verified (86.1) and PaperBench (93.0) with native vision-in-the-loop. Fable 5.1 leads the newer OSWorld 2.0 partial split (77.9) among Claude-class models.",
  },
  {
    id: "selfhost",
    title: "Apache/MIT self-host",
    pick: "hy4",
    alt: "glm",
    why: "Hy4 Preview is Apache 2.0 at 770B. GLM-5.3 Flash is MIT, smaller (320B/18B), cheaper to serve, and natively multimodal. Kimi K3 is stronger but custom-licensed.",
  },
];

const SOURCES = [
  { label: "Anthropic — Claude Fable 5.1 / Mythos 5.1", href: "https://www.anthropic.com/claude-fable-and-mythos-5-1" },
  { label: "Google — Gemini 3.8 Flash", href: "https://blog.google/innovation-and-ai/models-and-research/gemini-models/3-8-flash-and-3-8-flash-cyber/" },
  { label: "Moonshot — Kimi K3", href: "https://www.kimi.ai/blog/kimi-k3" },
  { label: "Tencent — Hy4 Preview", href: "https://www.tencent.com/tencent-releases-and-open-sources-tencent-hy4-preview/" },
  { label: "Z.ai — GLM-5.3 Flash", href: "https://z.ai/blog/glm-5.3-flash" },
  { label: "OpenAI — GPT-5.6 Cyber / Daybreak", href: "https://openai.com/index/expanding-daybreak-as-the-cyber-defense-window-narrows/" },
  { label: "Alibaba — Qwen3.8-Max", href: "https://www.alibabacloud.com/blog/603421" },
  { label: "Meta — Muse Glimmer 30B", href: "https://huggingface.co/meta-models/Muse-Glimmer-30B" },
];
